In [1]:
import pandas as pd

In [32]:
data = pd.read_csv("C:\\Users\\Braja\\Desktop\\Data Science\\Projects\\NLP\\Named Entity Recognition\\ner_dataset.csv", encoding='unicode_escape')
data.head(30)

Sentence #           Word  POS    Tag
0   Sentence: 1      Thousands  NNS      O
1           NaN             of   IN      O
2           NaN  demonstrators  NNS      O
3           NaN           have  VBP      O
4           NaN        marched  VBN      O
5           NaN        through   IN      O
6           NaN         London  NNP  B-geo
7           NaN             to   TO      O
8           NaN        protest   VB      O
9           NaN            the   DT      O
10          NaN            war   NN      O
11          NaN             in   IN      O
12          NaN           Iraq  NNP  B-geo
13          NaN            and   CC      O
14          NaN         demand   VB      O
15          NaN            the   DT      O
16          NaN     withdrawal   NN      O
17          NaN             of   IN      O
18          NaN        British   JJ  B-gpe
19          NaN         troops  NNS      O
20          NaN           from   IN      O
21          NaN           that   DT      O
22          NaN        country   NN      O
23          NaN              .    .      O
24  Sentence: 2       Families  NNS      O
25          NaN             of   IN      O
26          NaN       soldiers  NNS      O
27          NaN         killed  VBN      O
28          NaN             in   IN      O
29          NaN            the   DT      O

In [33]:
def get_dict_map(data, token_or_tag):
    toktag2idx = {}
    idx2toktag = {}
    
    if token_or_tag == 'token':
        uniquetoktag = list(set(data['Word'].to_list()))
    else:
        uniquetoktag = list(set(data['Tag'].to_list()))
    
    idx2toktag = {a:b for a,b in enumerate(uniquetoktag)}
    toktag2idx = {b:a for a,b in enumerate(uniquetoktag)}
    
    return idx2toktag, toktag2idx

idx2tok, tok2idx = get_dict_map(data, 'token')
idx2tag, tag2idx = get_dict_map(data, 'tag')

In [43]:
data['word_idx'] = data['Word'].map(tok2idx)
data['tag_idx'] = data['Tag'].map(tag2idx)

data_fillna = data.fillna(method='ffill', axis=0)

data_group = data_fillna.groupby(['Sentence #'],as_index=False)['Word','POS','Tag','word_idx','tag_idx'].agg(lambda x: list(x))

C:\Users\Braja\AppData\Local\Temp/ipykernel_7896/1329084630.py:6: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  data_group = data_fillna.groupby(['Sentence #'],as_index=False)['Word','POS','Tag','word_idx','tag_idx'].agg(lambda x: list(x))


In [58]:
data_group[data_group['Sentence #']=='Sentence: 1']['Word']

0    [Thousands, of, demonstrators, have, marched, ...
Name: Word, dtype: object

In [59]:
import xlwings

In [60]:
a = [1,2,3,4,5,2,1,4]

In [61]:
a.count(1)

2

In [62]:
{i:a.count(i) for i in a}

{1: 2, 2: 2, 3: 1, 4: 2, 5: 1}

In [63]:
[[i,a.count(i)] for i in a]

[[1, 2], [2, 2], [3, 1], [4, 2], [5, 1], [2, 2], [1, 2], [4, 2]]

In [78]:
[[j,"Count= "+str({i:a.count(i) for i in a}[j])] for j in {i:a.count(i) for i in a}]

[[1, 'Count= 2'],
 [2, 'Count= 2'],
 [3, 'Count= 1'],
 [4, 'Count= 2'],
 [5, 'Count= 1']]

In [75]:
for j in {i:a.count(i) for i in a}:
    print([j,{i:a.count(i) for i in a}[j]])

[1, 2]
[2, 2]
[3, 1]
[4, 2]
[5, 1]


In [74]:
{i:a.count(i) for i in a}[1]

2

In [79]:
import threading
  
def print_cube(num):
    """
    function to print cube of given num
    """
    print("Cube: {}".format(num * num * num))
  
def print_square(num):
    """
    function to print square of given num
    """
    print("Square: {}".format(num * num))

In [83]:
if __name__ == "__main__":
    # creating thread
    t1 = threading.Thread(target=print_square, args=(10,))
    t2 = threading.Thread(target=print_cube, args=(10,))
  
    # starting thread 1
    t1.start()
    # starting thread 2
    t2.start()
  
    # wait until thread 1 is completely executed
    t1.join()
    # wait until thread 2 is completely executed
    t2.join()
  
    # both threads completely executed
    print("Done!")

Square: 100
Cube: 1000
Done!


In [85]:
a = 'abcde'

In [88]:
a = 'ggh'

In [94]:
a[1]='d'

TypeError: 'str' object does not support item assignment

In [90]:
x = (1,2,3,1)

In [93]:
x=(2,3)

In [111]:
a = [1,2,4,5,2,5]

In [115]:
b = np.array(a)

In [117]:
a[:-1]

[1, 2, 4, 5, 2]

In [97]:
def squre(a):
    return a*a

In [98]:
import numpy as np

In [108]:
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [107]:
np.arange(3)

array([0, 1, 2])

In [118]:
array=np.array([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [48,5,6], [7,88,9]]])

In [119]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2,  3],
        [48,  5,  6],
        [ 7, 88,  9]]])

In [121]:
a = [-2,1,-3,4,-1,2,1,-5,4]

In [122]:
b = [-2,1]